version: "3.7"

services:
#  backend:
#    build: .
#    container_name: backend
#    hostname: backend
#    command: >
#      sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
#    env_file:
#       - .env
#    ports:
#      - "8000:8000"
#    environment:
#      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
#    depends_on:
#      - redis

#  redis:
#    image: redis:latest
#    container_name: redis
#    ports:
#      - "6379:6379"

#  celery_worker:
#    build: .
#    container_name: worker
#    command: celery -A comments worker --loglevel=info
#    env_file:
#      - .env
#    environment:
#      - BROKER_URL=amqp://guest:guest@rabbitmq:5672//
#    depends_on:
#      - rabbitmq-container
#    restart: on-failure

  rabbit:
    hostname: rabbit
    image: rabbitmq:3.8
    expose:
      - 5672
