# Generated by Django 4.2.5 on 2023-09-05 17:58

import comments.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_comment_homepage_alter_comment_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, storage=comments.utils.select_file_storage, upload_to=comments.utils.gen_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['txt', 'png', 'jpeg', 'gif'])]),
        ),
    ]
